name: Krishna Reels Auto Upload

on:
  workflow_dispatch:
  schedule:
    # 7:00 AM IST = 01:30 UTC
    - cron: "30 1 * * *"
    # 8:15 PM IST = 14:45 UTC
    - cron: "45 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Load API Keys
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "YT_CLIENT_ID=${{ secrets.YT_CLIENT_ID }}" >> $GITHUB_ENV
          echo "YT_CLIENT_SECRET=${{ secrets.YT_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "YT_REFRESH_TOKEN=${{ secrets.YT_REFRESH_TOKEN }}" >> $GITHUB_ENV

      - name: Generate Image With Auto Hindi Text
        run: python create_image.py

      - name: Create Video
        run: python create_video.py

      - name: Upload to YouTube
        run: python youtube_upload.py output/reel.mp4
